import Navbar from "@/components/navbar/Navbar";
import "@/app/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ Component, pageProps }) {
  return (
    <div className="full-height">
      <Component {...pageProps} />
      <Navbar />
    </div>
  );
}
